<?xml version="1.0"?>
<package format="2">
  <name>peak_cam</name>
  <version>0.1.0</version>
  <description>ROS 2 launch and configuration package for IDS cameras using camera_aravis2</description>

  <maintainer email="sherif.nekkah@gmail.com">Sherif Nekkah</maintainer>
  <maintainer email="evanflynn.msu@gmail.com">Evan Flynn</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <exec_depend>camera_aravis2</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
